#namePrefix: test-

bases:
  - ../../ipfs-cluster-base
#  - ../../ipfs-cluster-ingress-base

resources:
  - resources/secret.yaml
  - resources/ingress.yaml

patchesStrategicMerge:
  - patches/volumeclaim-patch.yaml
  - patches/env-configmap.yaml
  - patches/statefulset-annotations-patch.yaml
  - patches/service-patch.yaml
