apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster
spec:
  type: LoadBalancer
  ports:
    - name: api-http
      targetPort: api-http
      port: 9094
    - name: proxy-http
      targetPort: proxy-http
      port: 9095
