namePrefix: test-

bases:
  - ../../ipfs-cluster-base
  - ../../ipfs-cluster-ingress-base

resources:
  - secret.yaml

patchesStrategicMerge:
  - volumeclaim-patch.yaml
  - env-configmap.yaml
  - statefulset-annotations-patch.yaml
  - service-patch.yaml
