apiVersion: v1
kind: PersistentVolume
metadata:
    name: local-pv-06-2
spec:
    capacity:
        storage: 100Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    local:
        path: /data/local-pv-06-2
    nodeAffinity:
     required:
       nodeSelectorTerms:
       - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values:
           - ubuntu-06

