apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ipfs-cluster
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
    - host: ipfs-api.dev.gl-ets.gimbalabs.io
      http:
        paths:
          - path: /
            backend:
              serviceName: ipfs-cluster
              servicePort: api-http

